pipeline {
     agent {
        docker {
            image 'node'
        }
    }
    stages {
         stage('console log start') {
             steps{
                echo "starting.."
            } 
        }
        stage('npm install') {
            steps{
                sh 'npm install'
            }  
        }
        stage('build') {
            steps{
                sh 'ng build'
            } 
        }
        stage('console log end') {
             steps{
                echo "deploying.."
            } 
        }
    }
}